In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

print("Everything is working!")
print("Pandas:", pd.__version__)
print("Scikit-learn:", sklearn.__version__)

Everything is working!
Pandas: 2.3.3
Scikit-learn: 1.6.1

In [18]:
dataset = pd.read_csv("../Data/synthetic_training_data.csv")

In [20]:
dataset.head(10)

,student_id,exercise_is_correct_ratio,exercise_completion_velocity,practice_problems_solved,quiz_score,avg_exercise_attempts,avg_exercise_execution_time_ms,predicted_pass_probability,risk_level
0,1,0.59,382.3,54,13.0,9.4,5330,0.764,LOW
1,2,0.27,364.6,87,95.4,9.0,4963,0.814,LOW
2,3,0.48,315.4,48,34.7,4.4,9180,0.658,MEDIUM
3,4,0.43,192.0,65,56.6,7.0,995,0.616,MEDIUM
4,5,0.74,157.5,53,20.9,8.6,5240,0.718,LOW
5,6,0.29,560.6,83,50.9,5.9,873,0.922,LOW
6,7,0.44,296.3,42,35.6,2.4,2467,0.660,MEDIUM
7,8,0.60,391.8,92,75.5,8.1,5220,0.976,LOW
8,9,0.26,147.6,69,92.0,3.5,7310,0.484,MEDIUM
9,10,0.59,207.0,52,10.3,5.9,8420,0.561,MEDIUM

In [21]:
dataset.tail(10)

,student_id,exercise_is_correct_ratio,exercise_completion_velocity,practice_problems_solved,quiz_score,avg_exercise_attempts,avg_exercise_execution_time_ms,predicted_pass_probability,risk_level
4990,4991,0.49,125.0,64,93.7,1.8,8463,0.802,LOW
4991,4992,0.79,52.3,64,31.3,8.8,7764,0.727,LOW
4992,4993,0.05,340.8,33,87.5,1.3,3489,0.306,HIGH
4993,4994,0.16,302.8,29,85.3,1.5,9762,0.314,HIGH
4994,4995,0.52,491.4,50,9.1,2.3,6705,0.880,LOW
4995,4996,0.47,578.1,78,19.7,9.8,1927,0.929,LOW
4996,4997,0.89,472.3,81,69.2,1.3,9601,0.998,LOW
4997,4998,0.14,390.1,13,34.3,8.4,4823,0.092,HIGH
4998,4999,0.92,406.0,50,27.4,2.4,2075,0.989,LOW
4999,5000,0.62,342.7,84,66.9,7.4,5036,0.960,LOW

In [ ]:
student_id = int(input("Enter student ID: "))

dataset[dataset["student_id"] == student_id]

NameError: name 'student_id' is not defined